/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class KeyboardManager {
  close(): void
  onPlugged(callback: (kb: JsKeyboard) => void): void
  onUnplugged(callback: (kb: JsKeyboard) => void): void
  onPressed(callback: (kb: JsKeyboard) => void): void
  getKeyboards(): Array<JsKeyboard>
}

export interface JsKeyboard {
  keyboardId: JsKeyboardId
  portId: JsPortId
}

export interface JsKeyboardId {
  name?: string
  vendorId?: string
  productId?: string
  serial?: string
}

export interface JsPortId {
  physicalPath?: string
}

export declare function newKeyboardSource(): Promise<KeyboardManager>
